services:
  bot:
    container_name: go-twitter-download-bot
    image: go-twitter-download-bot
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - bot-data:/data
    command: /cli bot start -d /data/ -s /data/session.json -f ${FORWARD_TO_ID:-0} -U -T -B -l
    environment:
      - APP_ID=${APP_ID}
      - APP_HASH=${APP_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
volumes:
  bot-data:
